import "~/styles/globals.css";
import "@radix-ui/themes/styles.css";

import { Inter } from "next/font/google";
import NavBar from "~/components/NavBar";
import { getServerAuthSession } from "~/server/auth";
import QueryProvider from "./QueryProvider";
import { ChakraProvider } from "@chakra-ui/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();

  return (
    <html lang="en">
      <body className={`bg-[#f9f8f8] font-sans ${inter.variable}`}>
        <ChakraProvider>
          <QueryProvider>
            <NavBar session={session ?? null} />
            {children}
          </QueryProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
